goldmark:
    renderer:
        unsafe: false
tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 1
highlight:
    noClasses: true 
    codeFences: true
    guessSyntax: true
    lineNumbersInTable: false
    tabWidth: 2